entity_type_groups:
  node:
    article:
      basic: basic
    blog:
      basic: basic
    page:
      basic: basic
    portfolio:
      basic: basic
    service_pages:
      basic: basic
      open_graph: open_graph
    testimonial:
      basic: basic
    webform:
      basic: basic
  webform_submission:
    contact:
      basic: basic
    contact_us:
      basic: basic
    template_contact:
      basic: basic
